group: travis_latest
language: python
cache: pip
python:
    - 2.7
    - 3.5
    - 3.6
# Enable newer 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  allow_failures:
    - python: 3.8-dev
    - python: 3.5
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8-dev
      dist: xenial
      sudo: true
install: "make"
before_script:
    - make lint
script:
    - make test
after_success:
    # send report to https://coveralls.io/github/paragbaxi/qualysapi
    - coveralls
notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down
